//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkOrdersAppEntities : DbContext
    {
        public WorkOrdersAppEntities()
            : base("name=WorkOrdersAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ManageDevice> ManageDevices { get; set; }
        public virtual DbSet<refDevice> refDevices { get; set; }
        public virtual DbSet<refJob> refJobs { get; set; }
        public virtual DbSet<refUser> refUsers { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<refSite> refSites { get; set; }
    }
}
