//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageDevice
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int DeviceID { get; set; }
        public string DeviceGUID { get; set; }
        public Nullable<int> LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual refDevice refDevice { get; set; }
        public virtual refUser refUser { get; set; }
        public virtual refUser refUser1 { get; set; }
    }
}
