//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class refJob
    {
        public refJob()
        {
            this.WorkOrders = new HashSet<WorkOrder>();
        }
    
        public int ID { get; set; }
        public string JobName { get; set; }
        public bool Enabled { get; set; }
        public int SiteID { get; set; }
        public string JobNumber { get; set; }
    
        public virtual refSite refSite { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}
