//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public int ID { get; set; }
        public int JobID { get; set; }
        public int SubmitUserID { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Reviewed { get; set; }
        public Nullable<int> LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<decimal> RegHoursWorked { get; set; }
        public Nullable<decimal> OvertimeHoursWorked { get; set; }
    
        public virtual refUser refUser { get; set; }
        public virtual refJob refJob { get; set; }
        public virtual refUser refUser1 { get; set; }
    }
}
